telegram.bot:
  name: ${K_SHUFFLER_BOT_NAME}
  token: ${K_SHUFFLER_TOKEN}

spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://${K_SHUFFLER_DB_SERVER_HOST:localhost}:${K_SHUFFLER_DB_SERVER_PORT:5432}/${K_SHUFFLER_DB_NAME:ks_db}${K_SHUFFLER_DB_URL_PARAMS:}
  username: ${K_SHUFFLER_DB_USER:ks_bot}
  password: ${K_SHUFFLER_DB_PASSWORD:kicker}

spring.flyway:
  out-of-order: false
  enabled: true
  locations:
    - classpath:db/migration

server:
  port: ${K_SHUFFLER_PORT:6509}
  forward-headers-strategy: native
  servlet:
    context-path: /api
    session:
      cookie:
        http-only: true
  tomcat:
    max-connections: 10000
    threads:
      max: 1000
      min-spare: 50

rating:
  team-build-strategy: ${K_SHUFFLER_TEAM_BUILD_STRATEGY:random}
  spread-distance: ${K_SHUFFLER_RATING_SPREAD:100}