telegram.bot:
  name: ${K_SHUFFLER_BOT_NAME}
  token: ${K_SHUFFLER_TOKEN}

spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${K_SHUFFLER_DB_SERVER_HOST:localhost}:${K_SHUFFLER_DB_SERVER_PORT:5432}/${K_SHUFFLER_DB_NAME:shuffler_local}${K_SHUFFLER_DB_URL_PARAMS:}
    username: ${K_SHUFFLER_DB_USER:local}
    password: ${K_SHUFFLER_DB_PASSWORD:root}
  flyway:
    out-of-order: false
    enabled: true
    locations:
      - classpath:db/migration

rating:
  team-build-strategy: ${K_SHUFFLER_TEAM_BUILD_STRATEGY:random}
  spread-distance: ${K_SHUFFLER_RATING_SPREAD:100}